name: Check Quality
description: Check code Quality

runs:
  using: composite
  steps:
    - name: Lint code
      run: npm run lint
      shell: bash

    - name: Unit tests
      run: npm run tests
      shell: bash
