name: Check Quality
description: Check code Quality

inputs:
  deploy-url:
    description: 'Deployment url'
    required: true
    default: 'http://localhost:3000'

runs:
  using: composite
  steps:
    - name: Run e2e
      run: npm run test:e2e
      env:
        E2E_BASE_URL: ${{ inputs.deploy-url }}
      shell: bash
